_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 43
                - 53
                - 55
            "2":
                - 1
                - 5
                - 9
                - 41
                - 43
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
config_file:
    value: ../configs/COCO-Detection/faster_rcnn_R_101_FPN_3x_TRASH.yaml
dist_url:
    value: tcp://127.0.0.1:49152
eval_only:
    value: true
machine_rank:
    value: 0
num_gpus:
    value: 1
num_machines:
    value: 1
opts:
    value: []
resume:
    value: false
