_BASE_: "../Base-RCNN-FPN_TRASH.yaml"
MODEL:
  WEIGHTS: "/data/ephemeral/home/level2-objectdetection-cv-01/detectron2/tools/output/model_final_y.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 10
    SCORE_THRESH_TEST: 0.3
SOLVER:
  STEPS: (8000,12000)
  MAX_ITER: 15000
  GAMMA: 0.005
  CHECKPOINT_PERIOD: 3000
OUTPUT_DIR: '../../output'